In [92]:
# import library
from scipy.stats import f_oneway
import pandas as pd

In [93]:
# Readig Data
data = pd.read_csv("C:\\Benion\\Benion Programmings\\Python\\AI & ML\\data\\diets weight.csv")
data.shape

(4, 7)

In [94]:
# Present Data in Table
data.head()

Treatments  Location 1  Location 2  Location 3  Location 4  \
0        Diet 1         9.4         8.4         6.9         7.8   
1        Diet 2         7.5         5.2         5.6         5.7   
2        Diet 3         8.6         8.8         5.8         7.9   
3  Block Totals        25.5        22.4        18.3        21.4   

   Treatment Total  Treatment Means  
0             32.5             8.13  
1             24.0             6.00  
2             31.1             7.78  
3              NaN              NaN

In [95]:
# Extract diet values
diet_1 = data[0:1].values.reshape(1, -1)[0][1:5]
diet_2 = data[1:2].values.reshape(1, -1)[0][1:5]
diet_3 = data[2:3].values.reshape(1, -1)[0][1:5]
[diet_1, diet_2, diet_3]

[array([9.4, 8.4, 6.9, 7.8], dtype=object),
 array([7.5, 5.2, 5.6, 5.7], dtype=object),
 array([8.6, 8.8, 5.8, 7.9], dtype=object)]

In [96]:
# Extract location values
location_1 = data['Location 1'].values.reshape(1, -1)[0][:3]
location_2 = data['Location 2'].values.reshape(1, -1)[0][:3]
location_3 = data['Location 3'].values.reshape(1, -1)[0][:3]
location_4 = data['Location 4'].values.reshape(1, -1)[0][:3]
[location_1, location_2, location_3, location_4]

[array([9.4, 7.5, 8.6]),
 array([8.4, 5.2, 8.8]),
 array([6.9, 5.6, 5.8]),
 array([7.8, 5.7, 7.9])]

In [97]:
# Anova for diets
diet_anova = f_oneway(diet_1, diet_2, diet_3)
diet_anova

F_onewayResult(statistic=3.863786688714347, pvalue=0.06146714562860119)

In [98]:
# Anova for locations
location_anova = f_oneway(location_1, location_2, location_3, location_4)
location_anova

F_onewayResult(statistic=1.7175361612221671, pvalue=0.24029507773285838)