In [63]:
# import library
from scipy.stats import f_oneway, chisquare
import pandas as pd

In [64]:
# Readig Data
data = pd.read_csv("C:\\Benion\\Benion Programmings\\Python\\AI & ML\\data\\example-3.csv")
data.shape

(5, 8)

In [65]:
# Present Data in Table
data.head()

treatments  observation 1  observation 2  observation 3  observation 4  \
0  treatment  15              7              7             15             11   
1  treatment  20             12             17             12             18   
2  treatment  25             14             18             18             19   
3  treatment  30             19             25             22             19   
4  treatment  35              7             10             11             15   

   observation 5  total  mean  
0              9     49   9.8  
1             18     77  15.4  
2             19     88  17.6  
3             23    108  21.6  
4             11     54  10.8

In [66]:
# Extract treatment values
treatment_15 = data[0:1].values.reshape(1, -1)[0][1:6]
treatment_20 = data[1:2].values.reshape(1, -1)[0][1:6]
treatment_25 = data[2:3].values.reshape(1, -1)[0][1:6]
treatment_30 = data[3:4].values.reshape(1, -1)[0][1:6]
treatment_35 = data[4:].values.reshape(1, -1)[0][1:6]
[treatment_15, treatment_20, treatment_25, treatment_30, treatment_35]

[array([7, 7, 15, 11, 9], dtype=object),
 array([12, 17, 12, 18, 18], dtype=object),
 array([14, 18, 18, 19, 19], dtype=object),
 array([19, 25, 22, 19, 23], dtype=object),
 array([7, 10, 11, 15, 11], dtype=object)]

In [67]:
# Extract observation values
observation_1 = data['observation 1'].values.reshape(1, -1)[0]
observation_2 = data['observation 2'].values.reshape(1, -1)[0]
observation_3 = data['observation 3'].values.reshape(1, -1)[0]
observation_4 = data['observation 4'].values.reshape(1, -1)[0]
observation_5 = data['observation 5'].values.reshape(1, -1)[0]
[observation_1, observation_2, observation_3, observation_4, observation_5]

[array([ 7, 12, 14, 19,  7], dtype=int64),
 array([ 7, 17, 18, 25, 10], dtype=int64),
 array([15, 12, 18, 22, 11], dtype=int64),
 array([11, 18, 19, 19, 15], dtype=int64),
 array([ 9, 18, 19, 23, 11], dtype=int64)]

In [68]:
# Anova for treatments
treatment_anova = f_oneway(treatment_15, treatment_20, treatment_25, treatment_30, treatment_35)
treatment_anova

F_onewayResult(statistic=14.756823821339955, pvalue=9.127937124058432e-06)

In [69]:
# Anova for observations
observation_anova = f_oneway(observation_1, observation_2, observation_3, observation_4, observation_5)
observation_anova

F_onewayResult(statistic=0.6030964109781843, pvalue=0.66484791866385)